import os
import datetime

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    os.makedirs(directory, exist_ok=True)

    # Creating the markdown conent with metadata header
    markdown_content = f"""# 🌎 AI Travel Plan

    
    # # Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} 
    # **Created by:** Atriyo's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, expecially prices, operating hours, and availability before making any bookings or travel arrangements.*
    """

    try:

    # Write to markdown file with UTF-8 encoding
    # Generate timestamp-based filename 
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Travel_Plan_{timestamp}.md"

        print(filename)

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)

        print(f"Markdown file saved as: {filename}")
        return filename 

    except Exception as e:
        print(f"Error saving document: {e}")
        return None
